language: python
python:
  - "2.7"
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
# install dependencies from setup.py
  - pip install .
# install dependencies from requirements.txt
#   - pip install -r requirements.txt
# run nose tests
script: nosetests
# more information on configuring openshift deployments
# http://docs.travis-ci.com/user/deployment/openshift/
deploy:
  provider: openshift
  # Configure these values on your TravisCI 'Repository Settings' page:
  # http://docs.travis-ci.com/user/environment-variables/#Using-Settings
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  app: $OPENSHIFT_APP_NAME
  domain: $OPENSHIFT_APP_NAMESPACE
